# Start from the official Node.js 18 Alpine image
FROM node:18-alpine

# Define ARGs for user and group
ARG USER_NAME=rvl
ARG GROUP_NAME=rvl
ARG USER_ID=1001
ARG GROUP_ID=1001

# Create a non-root user and group
# RUN addgroup -g $GROUP_ID $GROUP_NAME && \
#     adduser -u $USER_ID -G $GROUP_NAME -s /bin/sh -D $USER_NAME

# Set the working directory
WORKDIR /app

# Change ownership of the working directory to the non-root user
# RUN chown -R $USER_NAME:$GROUP_NAME /app

# Switch to the non-root user
# USER $USER_NAME

# Copy package.json and package-lock.json (if available)
COPY  package*.json ./

RUN npm install

COPY  . .

# Expose the port your app runs on
EXPOSE 3000

